### ISSUE TITLE
Unexpected token �

### ISSUE THREAD

**Issue by iammerrick** [demerzel3/karma-sourcemap-loader#6]
I am getting the following error when I enable sourcemaps and using the style-loader: 

```
ERROR [karma]: [SyntaxError: Unexpected token �]
SyntaxError: Unexpected token �
    at Object.parse (native)
    at sourceMapData (/Users/Merrick/Developer/Domo/mobile-web/node_modules/karma-sourcemap-loader/index.js:9:29)
    at inlineMap (/Users/Merrick/Developer/Domo/mobile-web/node_modules/karma-sourcemap-loader/index.js:20:9)
    at /Users/Merrick/Developer/Domo/mobile-web/node_modules/karma-sourcemap-loader/index.js:47:9
    at nextPreprocessor (/Users/Merrick/Developer/Domo/mobile-web/node_modules/karma/lib/preprocessor.js:58:28)
    at /Users/Merrick/Developer/Domo/mobile-web/node_modules/karma-webpack/index.js:152:4
    at MemoryFileSystem.(anonymous function) [as readFile] (/Users/Merrick/Developer/Domo/mobile-web/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:206:10)
    at doRead (/Users/Merrick/Developer/Domo/mobile-web/node_modules/karma-webpack/index.js:117:32)
    at Plugin.readFile (/Users/Merrick/Developer/Domo/mobile-web/node_modules/karma-webpack/index.js:120:3)
    at process._tickCallback (node.js:419:13)
```

**Comment by demerzel3** [comment]
I close this issue for lack of updates, please add a comment if you still have this problem.

**Comment by jeffling** [comment]
Hey, I'll check on this after updating all my packages tomorrow :) I fixed sourcemaps for angular so I actually want this feature again.
